name: Test
on:
  push:
    branches:
      - master
      - stable*
  pull_request:

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up php${{ matrix.php-versions }}
      uses: shivammathur/setup-php@v2
    - name: Install Dependencies
      run: composer install --prefer-dist
    - name: Prepare MySQL database
      run: |
        sudo systemctl start mysql
        mysql -u root -proot -e "CREATE DATABASE oc_autotest;"
        mysql -u root -proot -e "CREATE USER 'oc_autotest'@'localhost' IDENTIFIED BY '';"
        mysql -u root -proot -e "GRANT ALL ON oc_autotest.* TO 'oc_autotest'@'localhost';"
    - name: Prepare Nextcloud server
      working-directory: ../
      run: |
        git clone https://github.com/nextcloud/server.git --recursive --depth 1 -b master server
        cp -r notes server/apps/
    - name: Setup Nextcloud server
      working-directory: ../server/
      run: |
        php occ maintenance:install --database-name oc_autotest --database-user oc_autotest --admin-user admin --admin-pass admin --database mysql --database-pass=''
        OC_PASS=test php occ user:add --password-from-env --display-name="Test" test
    - name: Setup Notes app
      working-directory: ../server/
      run: |
        php occ app:enable notes
        php occ app:check-code notes
    - name: Start Nextcloud server
      working-directory: ../server/
      run: "php -S localhost:8080 &"
    - name: Test API
      run: make test-api

